### ISSUE TITLE
Build failure on GHC 7.10 and lens 4.9.1

### ISSUE THREAD

**Issue by cstrahan** [iand675/hs-mesos#4]
I'm updating mesos from 0.21.0 to 0.22.0 in nixpkgs, and in the process of testing, it appears that hs-mesos doesn't build with GHC 7.10 and lens 4.9.1:

    Building hs-mesos-0.20.2.0...
    Preprocessing library hs-mesos-0.20.2.0...
    [ 1 of 42] Compiling System.Mesos.Types ( src/System/Mesos/Types.hs, dist/build/System/Mesos/Types.o )
    [ 2 of 42] Compiling System.Mesos.Resources ( src/System/Mesos/Resources.hs, dist/build/System/Mesos/Resources.o )
    [ 3 of 42] Compiling System.Mesos.TaskStatus ( src/System/Mesos/TaskStatus.hs, dist/build/System/Mesos/TaskStatus.o )
    [ 4 of 42] Compiling System.Mesos.Lens ( src/System/Mesos/Lens.hs, dist/build/System/Mesos/Lens.o )
    
    src/System/Mesos/Lens.hs:27:1:
        Illegal variable name: ‘data’
        When splicing a TH declaration:
          class HasData s a | s -> a
        where data :: forall . Control.Lens.Type.Lens' s a

I'm not entirely sure what's going on.

**Comment by cstrahan** [comment]
Copying the relevant bits from [another discussion](https://github.com/khibino/haskell-relational-record/issues/13):

> The "type" is derived from a column name of the "Tabconst" table.
> 
> GHC prior to 7.10 permitted a record field to have a name that has a collision with the reserved identifiers in Haskell if the field are generated by TH. We cannot use such a record field without qualifier, but in writing code with HRR, we always use it with qualified name. That restriction was not a problem.
> 
> GHC 7.10 got not to permit such record fields even derived from TH. If a database table has a column that is the same name with a reserved identifier, compilation error occurs.

It looks like GHC 7.10.1 won't allow you to use `data` as an identifier.

**Comment by cstrahan** [comment]
Hey @iand675, would you mind renaming that field to support GHC 7.10? Perhaps something like `datum` would work? If you can give me a name, I'll give you a PR, if that'll make things easier :).

**Comment by iand675** [comment]
Hi there, so sorry that I missed this. I'm totally happy to fix the issue.

**Comment by iand675** [comment]
I'll cut a release tomorrow that renames the field.

**Comment by iand675** [comment]
Ah, by the way, I've given you commit access if you need to make future changes!

**Comment by cstrahan** [comment]
@iand675 Cool - thanks!

**Comment by iand675** [comment]
Fixed in 0.20.3.0
